In [1]:
import psycopg2
#import sqlalchemy as sq
import pandas as pd
import numpy as np
import mariadb
#import dask.dataframe as dd
import json
import os
import shutil
import subprocess
from pathlib import Path
import pyodbc
# import rpy2.robjects as robjects
# from rpy2.robjects import pandas2ri
import requests

In [2]:
import mariadb
import sys

username = "scoring"
password = "idkltb93e0eomejp"
host = 'spectral-msql-jul-24-backup-do-user-2276924-0.b.db.ondigitalocean.com'
port = 25060
database="farmlabv3_live"
# schema="farmlabv3_live"
# schema="historical"
def get_db_cursor():
    try:
        conn = mariadb.connect(
            user=username,
            password=password,
            host=host,
            port=port,
            database=database
    
        )
        return conn
    except mariadb.Error as e:
        print(f"Error connecting to MariaDB Platform: {e}")
        sys.exit(1)

conn = get_db_cursor()
cur = conn.cursor()

In [3]:
conn_lims = pyodbc.connect("Driver={SQL Server};"
                            "Server=192.168.5.18\CROPNUT;"
                            "Database=cropnuts;"
                            "uid=thomasTsuma;pwd=GR^KX$uRe9#JwLc6")
cursor_lims = conn_lims.cursor()

In [4]:
comparison_df = pd.read_csv("inputFiles/KALRO Test protocol.csv")

In [5]:
generated_df = comparison_df.copy(deep=True)

In [6]:
generated_df

,barcode,client_name,farm_name,crop,country_name,ph,phosphorus,potassium,Organic Matter,Yield Target,...,PLANTING.4,TOP DRESS,TOP DRESS.1,TOP DRESS.2,TOP DRESS.3,TOP DRESS.4,TOP DRESS.5,Age,Number of trees,Land size in acres
0,TEST-DS1-1660,KALRO,test,Maize,Kenya,high,high,high,low,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TEST-DS1-1661,KALRO,test,Maize,Kenya,optimum,high,optimum,low,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TEST-DS1-1662,KALRO,test,Maize,Kenya,low,high,low,low,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,MOP,NaN,NaN,NaN,NaN,NaN,NaN
3,TEST-DS1-1663,KALRO,test,Maize,Kenya,high,optimum,high,optimum,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TEST-DS1-1664,KALRO,test,Maize,Kenya,optimum,optimum,optimum,optimum,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,TEST-DS1-1769,KALRO,test,Tomatoes (Open field),Kenya,optimum,optimum,optimum,optimum,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,TEST-DS1-1770,KALRO,test,Tomatoes (Open field),Kenya,low,optimum,low,optimum,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,TEST-DS1-1771,KALRO,test,Tomatoes (Open field),Kenya,high,low,high,high,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,TEST-DS1-1772,KALRO,test,Tomatoes (Open field),Kenya,optimum,low,optimum,high,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,TEST-DS1-1773,KALRO,test,Tomatoes (Open field),Kenya,low,low,low,high,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# cursor_lims.execute("dbo.Fert_Query 46,0,0").fetchone()

In [8]:
_ = pd.read_sql("select * from clients where client_name ='KALRO'",con=conn_lims)

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_24636\2299688460.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql("select * from clients where client_name ='KALRO'",con=conn_lims)

In [9]:
_

,Client_Id,Client_Code,Client_Name,PostalAddress,PhysicalAddress,Fax,Email,Phone1,Phone2,Phone3,...,Result_In_ppm_and_mmols,Xero_Client_Name,Xero_Client_Id,Xero_Client,User_Portal_Access,sampleintakeMSG,labMSG,verificationMSG,approvalMSG,EmailInstruction
0,8048,CK272,Kalro,P.O.BOX 278\r\nBUSIA,,,,,,,...,False,KALRO,None,False,False,None,None,None,None,None
1,59054,CK626,KALRO,KARLO HQ,Nairobi,,Violet.Kirigua@kalro.org,,,,...,False,KALRO,None,False,False,,,,,None
2,62239,AGD982,Kalro,,,,soilabs@yahoo.co.uk,728074546,,,...,False,,None,False,False,None,None,None,None,None
3,62242,SPL48,KALRO,P.O. Box 14733-00800,National Agricultural Research Laboratories,None,fredmulef@gmail.com,728074546,,None,...,False,None,None,False,False,None,None,None,None,None

In [10]:
_ = pd.read_sql("select * from Crops where crop_name ='Maize'",con=conn_lims)

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_24636\1002819801.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql("select * from Crops where crop_name ='Maize'",con=conn_lims)

In [11]:
_

,Crop_Code,Crop_Name,Owner_Type,show_fertigation,show_comments,show_recommendation,show_soilCorrection,show_fertilizerprogram,InputProd_Type,Perc_N,...,LimeCalcMethod,DefaultPrice,CarbonFootprint,Activeingredient,AI_mg_L,PCPBRegNo,Class,PostHarvestInterval,Growingdays,SeedType
0,46,Maize,1,False,True,True,True,True,1,None,...,0,None,None,None,None,None,None,None,None,None

In [12]:
_ = pd.read_sql("select * from Farms where farm_name ='test'",con=conn_lims)

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_24636\2727941666.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql("select * from Farms where farm_name ='test'",con=conn_lims)

In [13]:
_.columns

Index(['Farm_Code', 'Client_Id', 'Farm_Name', 'PostalAddress',
       'PhysicalAddress', 'Fax', 'Email', 'Phone1', 'Phone2', 'Phone3',
       'Website', 'Active', 'DefaultManure', 'Contact_person', 'Paybill_No',
       'County_Id', 'Constituency_Id', 'Ward_Id', 'SalesRegion_Code',
       'Sector_Code', 'MapTypeId', 'SoilMoisture', 'CropScouting',
       'SpotSampling', 'ProjectMaps', 'PrecisionFarming', 'geojson',
       'SummarySector_Code', 'Country_id', 'Customerview', 'Fert_method_Id',
       'SalesRep_Code', 'LimeCalcMethod'],
      dtype='object')

In [14]:
for index, row in generated_df.iterrows():
    client = row['client_name']
    crop = row['crop']
    farm = row['farm_name']
    client_id = cursor_lims.execute(f"SELECT client_id FROM Clients WHERE client_name ='{client}'  AND Clients.client_type=6").fetchone()[0]
    print(client_id)
    crop_id = cursor_lims.execute(f"SELECT crop_code FROM Crops WHERE crop_name ='{crop}'").fetchone()[0]
    print(crop_id)
    farm_id = cursor_lims.execute(f"SELECT farm_code FROM Farms WHERE farm_name ='{farm}'").fetchone()[0]
    print(farm_id)
    conn_lims.rollback()
    queries = pd.read_sql(f"SET NOCOUNT ON;execute [Fert_Query] @crop_code={crop_id},@client_id={client_id},@farm_code=0", con=conn_lims)
    break

62242
46
5503

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_24636\2178805438.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  queries = pd.read_sql(f"SET NOCOUNT ON;execute [Fert_Query] @crop_code={crop_id},@client_id={client_id},@farm_code=0", con=conn_lims)

In [16]:
queries

,Fert_Program_ExprHead_Id,Fert_Program_Expr_Desc,Fertilizer,crop_code,Client_id,Farm_Code,scenario_id,Query,Scenario_Desc,ScenarioFertQuery
0,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P> high and soil Potassium > high,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
1,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P> high and soil Potassium = optimum,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
2,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P > high and soil potassium < low,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
3,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil Potassium > high,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
4,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil Potassium = optimum,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
5,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil potassium < low,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
6,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P < Low and soil Potassium > high,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
7,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P <low and soil Potassium = optimum,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
8,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P < low and soil potassium < low,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
9,109220,TOP DRESS N (BALANCE),1820,46,62242,0,NaN,\r\n SELECT ( N_Tot - Sum Of CAN +2.4 Mg + 5.6...,,
10,109221,TOP DRESS K20,101,46,62242,0,NaN,\r\n SELECT ( K2O_Tot - Sum Of K2O ) / MOP,,

In [17]:
queries['Query']

0     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
1     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
2     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
3     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
4     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
5     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
6     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
7     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
8     \r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...
9     \r\n SELECT ( N_Tot - Sum Of CAN +2.4 Mg + 5.6...
10           \r\n SELECT ( K2O_Tot - Sum Of K2O ) / MOP
Name: Query, dtype: object

In [18]:
queries

,Fert_Program_ExprHead_Id,Fert_Program_Expr_Desc,Fertilizer,crop_code,Client_id,Farm_Code,scenario_id,Query,Scenario_Desc,ScenarioFertQuery
0,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P> high and soil Potassium > high,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
1,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P> high and soil Potassium = optimum,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
2,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P > high and soil potassium < low,\r\n IF Phosphorus > High OF Phosphorus\r\n AN...
3,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil Potassium > high,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
4,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil Potassium = optimum,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
5,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P = optimum and soil potassium < low,\r\n IF Phosphorus >= Low OF Phosphorus\r\n AN...
6,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P < Low and soil Potassium > high,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
7,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P <low and soil Potassium = optimum,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
8,109219,100% P2O5 at Planting,<Scenario>,46,62242,0,22248.0,\r\n SELECT P2O5_Tot / Di- Ammonium Phosphate ...,soil P < low and soil potassium < low,\r\n IF Phosphorus < Low OF Phosphorus\r\n AND...
9,109220,TOP DRESS N (BALANCE),1820,46,62242,0,NaN,\r\n SELECT ( N_Tot - Sum Of CAN +2.4 Mg + 5.6...,,
10,109221,TOP DRESS K20,101,46,62242,0,NaN,\r\n SELECT ( K2O_Tot - Sum Of K2O ) / MOP,,